allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@sentry/browser-utils@10.69.0'
  - '@sentry/browser@10.69.0'
  - '@sentry/core@10.69.0'
  - '@sentry/feedback@10.69.0'
  - '@sentry/nextjs@10.69.0'
  - '@sentry/node-core@10.69.0'
  - '@sentry/node@10.69.0'
  - '@sentry/opentelemetry@10.69.0'
  - '@sentry/react@10.69.0'
  - '@sentry/replay-canvas@10.69.0'
  - '@sentry/replay@10.69.0'
  - '@sentry/server-utils@10.69.0'
  - '@sentry/vercel-edge@10.69.0'
  - stripe@22.4.0
